import "./globals.css";


export const metadata = {
  title: "Meet US Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="">
        {children}
      </body>
    </html>
  );
}
